// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../wie-ki-funktioniert/[lektionId]/page";
export const dynamicParams = false;
