import { SITE_ORIGIN } from "@/lib/seo/entity";

export const KNOWLEDGE_GRAPH_SCHEMA_ID =
  `${SITE_ORIGIN}/schema/knowledge-graph/v1` as const;

/**
 * Versioned JSON Schema for the public knowledge-graph response. Keep this
 * document free of private account, provider, and runtime configuration data.
 */
export const KNOWLEDGE_GRAPH_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: KNOWLEDGE_GRAPH_SCHEMA_ID,
  title: "loehrning.ai public knowledge graph",
  description:
    "Public learning-resource graph, locale representations, provenance, and catalog discovery metadata.",
  type: "object",
  additionalProperties: false,
  required: [
    "schema",
    "generatedAt",
    "site",
    "openSource",
    "nodes",
    "edges",
    "catalogs",
  ],
  properties: {
    schema: { const: KNOWLEDGE_GRAPH_SCHEMA_ID },
    generatedAt: { type: "string", format: "date-time" },
    site: {
      type: "object",
      additionalProperties: false,
      required: ["name", "url", "language", "openSourceHub"],
      properties: {
        name: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        language: {
          type: "array",
          minItems: 1,
          uniqueItems: true,
          items: { $ref: "#/$defs/pageLanguage" },
        },
        openSourceHub: { $ref: "#/$defs/uri" },
      },
    },
    openSource: {
      type: "object",
      additionalProperties: false,
      required: ["organization", "orgUrl", "sourcePolicy"],
      properties: {
        organization: { type: "string" },
        orgUrl: { $ref: "#/$defs/uri" },
        sourcePolicy: { type: "string" },
      },
    },
    nodes: {
      type: "array",
      items: { $ref: "#/$defs/learningNode" },
    },
    edges: {
      type: "array",
      items: { $ref: "#/$defs/learningEdge" },
    },
    catalogs: {
      type: "object",
      additionalProperties: false,
      required: [
        "books",
        "demos",
        "blog",
        "workshops",
        "openSourceLabs",
        "openSourceArtifacts",
      ],
      properties: {
        books: {
          type: "array",
          items: { $ref: "#/$defs/bookCatalogItem" },
        },
        demos: {
          type: "array",
          items: { $ref: "#/$defs/demoCatalogItem" },
        },
        blog: {
          type: "array",
          items: { $ref: "#/$defs/blogCatalogItem" },
        },
        workshops: {
          type: "array",
          items: { $ref: "#/$defs/workshopCatalogItem" },
        },
        openSourceLabs: {
          type: "array",
          items: { $ref: "#/$defs/openSourceLabCatalogItem" },
        },
        openSourceArtifacts: {
          type: "array",
          items: { $ref: "#/$defs/openSourceArtifactCatalogItem" },
        },
      },
    },
  },
  $defs: {
    uri: { type: "string", format: "uri" },
    date: { type: "string", format: "date" },
    pageLanguage: { type: "string", enum: ["de-DE", "en-GB"] },
    stringArray: {
      type: "array",
      items: { type: "string" },
    },
    localizedUrls: {
      type: "object",
      additionalProperties: false,
      required: ["de"],
      properties: {
        de: { $ref: "#/$defs/uri" },
        en: { $ref: "#/$defs/uri" },
      },
    },
    localizedPage: {
      type: "object",
      additionalProperties: false,
      required: ["url", "pageLanguage", "title"],
      properties: {
        url: { $ref: "#/$defs/uri" },
        pageLanguage: { $ref: "#/$defs/pageLanguage" },
        title: { type: "string" },
        summary: { type: ["string", "null"] },
        riskNotes: { $ref: "#/$defs/stringArray" },
        format: { type: "string" },
        duration: { type: "string" },
      },
    },
    localizedPages: {
      type: "object",
      additionalProperties: false,
      required: ["de"],
      properties: {
        de: { $ref: "#/$defs/localizedPage" },
        en: { $ref: "#/$defs/localizedPage" },
      },
    },
    localizedText: {
      type: "object",
      additionalProperties: false,
      required: ["de", "en"],
      properties: {
        de: { type: "string" },
        en: { type: "string" },
      },
    },
    localizedStringArrays: {
      type: "object",
      additionalProperties: false,
      required: ["de", "en"],
      properties: {
        de: { $ref: "#/$defs/stringArray" },
        en: { $ref: "#/$defs/stringArray" },
      },
    },
    learningNode: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "type",
        "title",
        "url",
        "canonicalPageLanguage",
        "availablePageLanguages",
        "sourceMaterialLanguages",
        "localizedPages",
        "access",
        "crawlClass",
        "evidenceMode",
        "sourceOwner",
        "courseSlug",
        "summary",
      ],
      properties: {
        id: { type: "string" },
        type: { type: "string" },
        title: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        canonicalPageLanguage: { $ref: "#/$defs/pageLanguage" },
        availablePageLanguages: {
          type: "array",
          minItems: 1,
          uniqueItems: true,
          items: { $ref: "#/$defs/pageLanguage" },
        },
        sourceMaterialLanguages: { $ref: "#/$defs/stringArray" },
        localizedPages: { $ref: "#/$defs/localizedPages" },
        access: { type: "string" },
        crawlClass: { type: "string" },
        evidenceMode: { type: "string" },
        sourceOwner: { type: "string" },
        courseSlug: { type: ["string", "null"] },
        summary: { type: ["string", "null"] },
      },
    },
    learningEdge: {
      type: "object",
      additionalProperties: false,
      required: ["from", "to", "type"],
      properties: {
        from: { type: "string" },
        to: { type: "string" },
        type: { type: "string" },
      },
    },
    bookCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "url",
        "localizedUrls",
        "lastReviewed",
        "nextReview",
        "sourceOwner",
      ],
      properties: {
        id: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        localizedUrls: { $ref: "#/$defs/localizedUrls" },
        lastReviewed: { $ref: "#/$defs/date" },
        nextReview: { $ref: "#/$defs/date" },
        sourceOwner: { type: "string" },
      },
    },
    demoCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "url",
        "sourceMaterialLanguages",
        "localizedPages",
        "lastReviewed",
        "evidenceMode",
      ],
      properties: {
        id: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        sourceMaterialLanguages: { $ref: "#/$defs/stringArray" },
        localizedPages: { $ref: "#/$defs/localizedPages" },
        lastReviewed: { $ref: "#/$defs/date" },
        evidenceMode: { type: "string" },
      },
    },
    blogCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "url",
        "localizedUrls",
        "datePublished",
        "dateModified",
        "tags",
        "localizedTitles",
        "localizedSummaries",
        "localizedTags",
      ],
      properties: {
        id: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        localizedUrls: { $ref: "#/$defs/localizedUrls" },
        datePublished: { $ref: "#/$defs/date" },
        dateModified: { $ref: "#/$defs/date" },
        tags: { $ref: "#/$defs/stringArray" },
        localizedTitles: { $ref: "#/$defs/localizedText" },
        localizedSummaries: { $ref: "#/$defs/localizedText" },
        localizedTags: { $ref: "#/$defs/localizedStringArrays" },
      },
    },
    workshopCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "url",
        "sourceMaterialLanguages",
        "localizedPages",
        "materialCount",
        "evidenceMode",
      ],
      properties: {
        id: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        sourceMaterialLanguages: { $ref: "#/$defs/stringArray" },
        localizedPages: { $ref: "#/$defs/localizedPages" },
        materialCount: { type: "integer", minimum: 0 },
        evidenceMode: { type: "string" },
      },
    },
    openSourceLabCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "url",
        "localizedUrls",
        "sourceUrl",
        "launchUrl",
        "sourceCommit",
        "licenseUrl",
      ],
      properties: {
        id: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        localizedUrls: { $ref: "#/$defs/localizedUrls" },
        sourceUrl: { $ref: "#/$defs/uri" },
        launchUrl: { $ref: "#/$defs/uri" },
        sourceCommit: { type: "string" },
        licenseUrl: { $ref: "#/$defs/uri" },
      },
    },
    openSourceArtifactCatalogItem: {
      type: "object",
      additionalProperties: false,
      required: [
        "id",
        "kind",
        "url",
        "localizedUrls",
        "sourceUrl",
        "sourceCommit",
        "licenseUrl",
        "accessUrl",
      ],
      properties: {
        id: { type: "string" },
        kind: { type: "string" },
        url: { $ref: "#/$defs/uri" },
        localizedUrls: { $ref: "#/$defs/localizedUrls" },
        sourceUrl: { $ref: "#/$defs/uri" },
        sourceCommit: { type: "string" },
        licenseUrl: { $ref: "#/$defs/uri" },
        accessUrl: { $ref: "#/$defs/uri" },
      },
    },
  },
} as const;
