/**
 * Shared certificate constants — imported by both the QR encoder
 * (certificate-pdf.ts) and the QR decoder (verification-page.tsx).
 *
 * Bump CERTIFICATE_QR_VERSION only when the QR payload schema changes.
 * Old QR codes with the previous version will be rejected by
 * verification-page and must be re-generated by the learner.
 */

export const CERTIFICATE_QR_VERSION = 1 as const;

/**
 * Which certificate-eligibility path a learner completed. "completion" (plan
 * 007 stage 4) is a strict addition to the QR payload's `m` field — every
 * existing "quiz"/"capstone" QR code still decodes, so it does not require a
 * CERTIFICATE_QR_VERSION bump.
 */
export type CertificateCompletionMode = "quiz" | "capstone" | "completion";
