#!/usr/bin/env node
/**
 * Loopback file server for the published Data Readiness workshop folder.
 *
 * The Workshop 03 card preview (card-preview.webp) used to be a Chromium screenshot of the
 * deck cover made here. It is now the 1200 x 630 poster card of all four workshops,
 * generated from src/lib/plakat by
 *   node packages/website/scripts/plakat/build-cards.mjs   (then --check)
 * after which node scripts/course03/refresh-published.mjs records its bytes in
 * bundle-manifest.json and in this workshop's ASSET_MANIFEST.json row. Running this file
 * directly only prints that pointer. resolvePreviewFile and createPreviewServer stay: they
 * are the reviewed containment rules for serving this folder on a loopback port.
 */
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const TYPES = { ".html": "text/html; charset=utf-8", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml", ".woff2": "font/woff2", ".ttf": "font/ttf", ".jpg": "image/jpeg", ".webp": "image/webp", ".json": "application/json" };

/**
 * Map a request target onto a file inside `folder`.
 *
 * Returns `{ file }` for a servable path, `{ status: 400 }` for a target that is not a
 * valid URL or whose percent-escapes do not decode, and `{ status: 403 }` for anything
 * outside the folder. Containment is exact: the resolved path must start with the
 * resolved folder plus a separator, so a sibling such as `<folder>-private/` that only
 * shares the folder's name as a string prefix is refused, and so is the folder itself.
 */
export function resolvePreviewFile(folder, requestTarget) {
  let pathname;
  try {
    pathname = decodeURIComponent(new URL(requestTarget, "http://localhost").pathname);
  } catch {
    return { status: 400 };
  }
  const root = path.resolve(folder);
  const inside = root.endsWith(path.sep) ? root : `${root}${path.sep}`;
  const file = path.resolve(root, `.${pathname}`);
  if (!file.startsWith(inside)) return { status: 403 };
  return { file };
}

/** A static file server for `folder` that answers only paths resolvePreviewFile accepts. */
export function createPreviewServer(folder) {
  return createServer(async (request, response) => {
    const target = resolvePreviewFile(folder, request.url ?? "/");
    if (!target.file) {
      response.writeHead(target.status).end();
      return;
    }
    try {
      const bytes = await readFile(target.file);
      response.writeHead(200, { "content-type": TYPES[path.extname(target.file)] ?? "application/octet-stream" }).end(bytes);
    } catch {
      response.writeHead(404).end();
    }
  });
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.error("The card preview is generated by packages/website/scripts/plakat/build-cards.mjs; then run node scripts/course03/refresh-published.mjs.");
  process.exit(2);
}
