// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../../kurse/open-source/data-science/[chapterSlug]/page";
export const dynamicParams = false;
