// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../open-source/[kind]/[slug]/page";
export const dynamicParams = false;
