#!/usr/bin/env python3
"""Assemble page/builder.html from the sources in this folder.

Numbers come from ../kit/builder/warehouse/seed/builder-data.json (generated by the seed) and
from the authored teaching content below. The anti-pattern index is parsed from
../kit/builder/ANTI-PATTERNS.md so the page and the kit never drift apart.
"""
import json, re, pathlib, html

HERE = pathlib.Path(__file__).resolve().parent
KIT = HERE.parent / "kit" / "builder"
OUT = HERE.parent / "page" / "builder.html"

seed = json.loads((KIT / "warehouse/seed/builder-data.json").read_text())
months = {m["month_start"][:7]: m for m in seed["months"]}


def mo(key, label):
    m = months[key]
    return {"key": key, "label": label, "end": m["ending_mrr_eur"], "chg": m["net_new_mrr_eur"]}


tub = [mo("2025-12", "Dec 2025"), mo("2026-01", "Jan 2026"), mo("2026-02", "Feb 2026"),
       mo("2026-03", "Mar 2026"), mo("2026-04", "Apr 2026"), mo("2026-05", "May 2026"),
       mo("2026-06", "Jun 2026")]

# Fixed facts: fail the build if the seed ever drifts from the deck.
assert [t["end"] for t in tub] == [258785, 272995, 294475, 354635, 334675, 344450, 387015]
assert [t["chg"] for t in tub[1:]] == [14210, 21480, 60160, -19960, 9775, 42565]
assert seed["q2"]["net_new_mrr_eur"] == 32380 and seed["q2"]["levels_summed_meaningless_eur"] == 1066140
assert seed["recorded_ai_answers"]["g01_export_lane_eur"] == [-19960, 9775, 42565]
assert seed["recorded_ai_answers"]["g02_export_lane_eur"] == -17595
assert seed["dry_runs"]["running_totals_from_january_eur"] == [75890, 85665, 128230]

# ---------------------------------------------------------------- anti-patterns
GROUPS = {"Q": "Question", "N": "Naming", "L": "Layers", "M": "Metrics", "S": "Serving views",
          "A": "Access", "C": "Claude", "F": "Freshness", "T": "Tests", "E": "Evidence"}
MODULES = {"Bathtub": "m1", "Can I add these?": "m2", "Semantic layer": "m3", "Layers": "m4",
           "Names": "m5", "Serving views": "m6", "Access": "m7", "Claude": "m8",
           "Freshness": "m9", "Tests": "m10", "Build": "m12"}
aps = []
for line in (KIT / "ANTI-PATTERNS.md").read_text().splitlines():
    if not line.startswith("| AP-"):
        continue
    cells = [c.strip() for c in line.strip().strip("|").split(" | ")]
    assert len(cells) == 7, line
    ident, symptom, inst, why, fix, caught, module = cells
    aps.append({"id": ident, "group": GROUPS[ident[3]], "symptom": symptom, "instance": inst,
                "why": why, "fix": fix, "caught": caught, "module": module,
                "anchor": MODULES[module]})
assert len(aps) == 49, len(aps)

# ---------------------------------------------------------------- authored content
data = {
    "question": seed["question"],
    "company": {k: seed["company"][k] for k in ("accounts", "per_segment", "segments", "account_months")},
    "tub": tub,
    "q2": {"start": 354635, "netNew": seed["q2"]["net_new_mrr_eur"], "end": 387015,
           "levelsSum": seed["q2"]["levels_summed_meaningless_eur"]},
    "recorded": {"g01": seed["recorded_ai_answers"]["g01_export_lane_eur"],
                 "g02": seed["recorded_ai_answers"]["g02_export_lane_eur"]},
    "dry": {"running": seed["dry_runs"]["running_totals_from_january_eur"], "march": 95850},
    "churn": {"start": 40, "churned": 4, "joined": 8, "end": 44, "pct": "10.0",
              "wrongBase": 48, "wrongPct": "8.33", "pooledStart": 120, "pooledChurned": 12},
    "active": {"apr": 123, "may": 123, "jun": 132, "distinctQ2": 141, "summed": 378, "perSegJun": 44},
    "expansionTotal": sum(r["expansion_mrr_eur"] for r in seed["g04_expansion_by_country_q2"]),
    "g04": seed["g04_expansion_by_country_q2"],
    "web": {"searchOrders": 400, "searchSessions": 20000, "emailRatePct": 8, "emailMin": 1000,
            "emailMax": 20000, "emailStep": 1000},
    "fresh": {"loaded": "2026-07-01 06:00 UTC", "loadedIso": "2026-07-01T06:00:00Z",
              "clockAge": 3, "warn": 36, "whatIf": 60, "max": 72, "invented": 48},
    "grain": {"accountMonth": 2592, "segmentMonth": 54, "month": 18, "accounts": 144, "monthsServed": 18},
    "trace": {"rows": 144, "withMrr": 123, "april": 334675},
    "checks": [
        ["G01", "answer", "2026-04-01 334675, 2026-05-01 344450, 2026-06-01 387015", "PASS"],
        ["G02", "answer", "32380", "PASS"],
        ["G03", "answer", "Enterprise 4/40=10.0, Mid-Market 4/40=10.0, SMB 4/40=10.0", "PASS"],
        ["G04", "answer", "CH 1990, DE 1780, FR 1780, SE 1780, NL 1655, PL 1640, AT 1565, GB 705", "PASS"],
        ["G05", "answer", "fl_0006 7705 ... fl_0087 7235 (10 rows)", "PASS"],
        ["D01", "deny", "42501 permission denied for schema core", "PASS"],
        ["B-W01", "deny", "42501 permission denied for schema analytics", "PASS"],
        ["B-T01", "deny", "42501 permission denied to create temporary tables", "PASS"],
        ["B-S01", "error", "42P01 undefined_table (search_path=\"\")", "PASS"],
        ["B-X01", "access", "no CONNECT on saas_bad", "PASS"],
        ["B-P01", "access", "5 x SELECT, all on analytics", "PASS"],
        ["Q01", "reconcile", "dups 0/0/0/0, rows 18/15/144/2592", "PASS"],
        ["Q02", "reconcile", "354635 + 32380 = 387015; breaks 0; parts 0", "PASS"],
        ["Q03", "reconcile", "last 2026-06-01, complete 2026-06-01, after 0, passing", "PASS"],
        ["Q04", "reconcile", "Enterprise 40-4+8=44, Mid-Market 40-4+8=44, SMB 40-4+8=44", "PASS"],
        ["Q05", "reconcile", "18 months, 0 mismatched", "PASS"],
        ["Q06", "reconcile", "5 of 5 views say definition 1.0.0", "PASS"],
        ["Q07", "lineage", "5 views: upstreams as declared in model.yml", "PASS"],
        ["T01", "answer", "141 distinct accounts; 378 account-months", "PASS"],
        ["T02", "answer", "2026-04-01 2720.93, 2026-05-01 2800.41, 2026-06-01 2931.93", "PASS"],
        ["F00", "freshness", "3 h, fresh: answer @ 2026-07-01T09:00", "PASS"],
        ["F01", "freshness", "60 h, stale_disclosed: answer with warning @ 2026-07-03T18:00", "PASS"],
    ],
    "runs": [
        {"id": "rec-exp", "when": "Aug 2026", "route": "Export tables", "cases": "G01–G03",
         "runs": "1 each", "values": "0 of 3", "cited": "n/a (not graded)", "note": "−\u2060€19,960 / €9,775 / €42,565; −\u2060€17,595; 0 of 0, no rate"},
        {"id": "rec-app", "when": "Aug 2026", "route": "Approved views", "cases": "G01–G03",
         "runs": "1 each", "values": "3 of 3", "cited": "0 of 3", "note": "SQL leaned on a search_path setting"},
        {"id": "dry-a", "when": "Rehearsal", "route": "Chat A: export CSVs", "cases": "G01",
         "runs": "2", "values": "0 of 2", "cited": "n/a (no definition loaded)", "note": "75,890 / 85,665 / 128,230 labelled Ending MRR"},
        {"id": "dry-b", "when": "Rehearsal", "route": "Project B: approved files", "cases": "7 cases",
         "runs": "1 each", "values": "4 of 4 answers (G01, F01, G02, G03)", "cited": "4 of 4 answers (C01, R01, R02: n/a)",
         "note": "Behaviour 7 of 7. Earlier file set; re-run on current files"},
    ],
    "aps": aps,
}

data.update(json.loads((HERE / "content.json").read_text()))


# ---------------------------------------------------------------- excerpts from the shipped files
def pick(src, segments):
    """Return the exact lines participants get: whole file, or segments joined by an ellipsis.

    Each segment is [regex, line_count]; it is searched after the previous segment, so the order
    of segments follows the file. A missing file or pattern fails the build: the page must never
    show a file the kit does not ship.
    """
    path = KIT / src
    assert path.is_file(), f"page shows {src}, but the kit has no such file"
    lines = path.read_text().splitlines()
    if not segments:
        return "\n".join(lines).strip()
    out, pos = [], 0
    for pattern, count in segments:
        rx = re.compile(pattern)
        hit = next((i for i in range(pos, len(lines)) if rx.search(lines[i])), None)
        assert hit is not None, f"{src}: no line matches {pattern!r} after line {pos}"
        if out:
            out.append("…")
        out.extend(lines[hit:hit + count])
        pos = hit + count
    return "\n".join(out)


for name, f in data["files"].items():
    f["excerpt"] = pick(f["src"], f.pop("pick"))
for r in data["readers"]:
    r["body"] = pick(r["src"], r.pop("pick"))
    assert "1.0.0" in r["body"], f"reader {r['id']} shows no version"
assert len(data["checks"]) == 22, len(data["checks"])
for s in data["setups"]:
    for d in s["tree"]:
        for fn in d["files"]:
            assert fn in data["files"], f"setup {s['id']} lists {fn}, which has no file entry"

# Assemble.
css = (HERE / "page.css").read_text()
body = (HERE / "body.html").read_text()
js = (HERE / "app.js").read_text()
icons = (HERE / "_icons.svg").read_text()
blob = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<meta name="theme-color" content="#f3f0e9">
<meta name="description" content="Build the approved lane for your own question: semantic layer, names, metrics, serving views, access, Claude setup, tests and a runbook, taught with the synthetic FOLDLINE case.">
<title>Builder guide</title>
<link rel="icon" href="./assets/favicon.svg">
<style>
{css}
</style>
</head>
<body>
<svg class="sprite" width="0" height="0" aria-hidden="true" focusable="false"><defs>
<pattern id="hatch" width="14" height="14" patternUnits="userSpaceOnUse"><rect width="14" height="14" fill="#f2f1ee"/><path d="M-3.5 3.5l7-7M0 14L14 0M10.5 17.5l7-7" stroke="#121212" stroke-width="2.12" stroke-linecap="square"/></pattern>
{icons}
</defs></svg>
{body}
<script type="application/json" id="builder-data">{blob}</script>
<script>
{js}
</script>
</body>
</html>
"""
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(page)
print(f"wrote {OUT} ({len(page):,} bytes, {len(aps)} anti-patterns)")
