// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../../../kurse/open-source/ai-native-operator/[moduleId]/[lessonNum]/page";
export const dynamicParams = false;
