import type { Locale } from "@/lib/i18n/locale";

export const COURSE_GALLERY_COPY = {
  de: {
    linkCopied: "Link kopiert",
    copyFailed: "Kopieren fehlgeschlagen",
    day: "Tag",
    days: "Tage",
    streak: "Serie",
    viewRecord: "Nachweis ansehen",
    continue: "Weiterlernen",
    start: "Kurs starten",
    step: "Schritt",
    completed: "abgeschlossen",
    achieved: "erreicht",
    features: "Merkmale",
    duration: "Dauer",
    scope: "Umfang",
    structure: "Aufbau",
    access: "Zugang",
    free: "Kostenlos",
    lessons: "Lektionen",
    details: "Kursdetails",
    shareProgress: "Fortschritt teilen",
    progress: "Fortschritt",
    progressLoaded: (completed: number, total: number) =>
      `${completed} von ${total} Lektionen abgeschlossen`,
    progressLoading: (title: string) => `Fortschritt ${title} wird geladen`,
    sourceCode: "Quellcode auf GitHub",
    sourceCommit: "Quell-Commit",
    onGitHub: "auf GitHub",
    coreFacts: "Kerndaten und Themen",
    openCourse: "Kurs öffnen",
    externalNewTab: "extern in neuem Tab",
    pendingDetails: "Details",
    workshopLead:
      "Angewandte Selbstlernmaterialien auf Basis von Workshop-Inhalten findest du unter",
  },
  en: {
    linkCopied: "Link copied",
    copyFailed: "Copy failed",
    day: "day",
    days: "days",
    streak: "streak",
    viewRecord: "View completion record",
    continue: "Continue course",
    start: "Start course",
    step: "Step",
    completed: "completed",
    achieved: "completed",
    features: "Course facts",
    duration: "Duration",
    scope: "Scope",
    structure: "Structure",
    access: "Access",
    free: "Free",
    lessons: "lessons",
    details: "Course details",
    shareProgress: "Share progress",
    progress: "Progress",
    progressLoaded: (completed: number, total: number) =>
      `${completed} of ${total} lessons completed`,
    progressLoading: (title: string) => `Loading progress for ${title}`,
    sourceCode: "Source code on GitHub",
    sourceCommit: "Source commit",
    onGitHub: "on GitHub",
    coreFacts: "Course facts and topics",
    openCourse: "Open course",
    externalNewTab: "external, opens in a new tab",
    pendingDetails: "Details",
    workshopLead:
      "Applied self-study materials based on workshop content are listed under",
  },
} as const satisfies Readonly<Record<Locale, Record<string, unknown>>>;
