// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../buecher/[slug]/[chapter]/page";
export const dynamicParams = false;
export const runtime = "nodejs";
