#!/usr/bin/env node
// Workshop 04 deck build: binds slides.html to the dataset and writes the generated files.
//
//   node scripts/workshop04/build-deck.mjs          write lib/w04-data.js, the generated fragments,
//                                                   every data-num / data-j text and presenter-notes.js
//   node scripts/workshop04/build-deck.mjs --check  change nothing; exit 1 if any output would change
//                                                   or a lint finding exists
//
// Inputs: scripts/workshop04/data/w04-data.json (built by data/build_dataset.py) and the presenter
// note sources in scripts/workshop04/notes/*.mjs. The resolver is the deck's own lib/w04-fill.js, so
// build time and run time format every number the same way.
//
// Generated fragments live between <!-- gen:NAME key=value … --> and <!-- /gen:NAME --> in
// slides.html; the text between the markers is replaced on every run.
//
// Lint (fails the build): a number in visible slide text that is not in the JSON (allowlist: years,
// day and scene counters up to 31, the 1920 × 1080 canvas and the legal references in LEGAL), an
// en or em dash anywhere in the deck files, a question card that is not the fixed question, an
// unresolved binding, a scene without presenter notes.

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import vm from "node:vm";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");
const DECK = path.join(REPO, "packages/website/public/workshops/esg-berichte-mit-ki");
const DATA_PATH = path.join(HERE, "data/w04-data.json");
const CHECK = process.argv.includes("--check");

const data = JSON.parse(readFileSync(DATA_PATH, "utf8"));
const context = { console };
context.globalThis = context;
vm.runInNewContext(readFileSync(path.join(DECK, "lib/w04-fill.js"), "utf8"), context);
const fillApi = context.W04Fill;

const findings = [];
const changed = [];

function write(file, content) {
  const target = path.join(DECK, file);
  const before = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (before === content) return;
  changed.push(file);
  if (!CHECK) writeFileSync(target, content);
}

const esc = (text) => String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const attr = (text) => esc(text).replace(/"/g, "&quot;");
const n = (key, form) => `<span class="num" data-num="${key}"${form ? ` data-form="${form}"` : ""}>${esc(fillApi.numberText(data, key, form))}</span>`;
const j = (p, form, cls = "") => `<span${cls ? ` class="${cls}"` : ""} data-j="${attr(p)}"${form ? ` data-form="${form}"` : ""}>${esc(fillApi.pathText(data, p, form) ?? "")}</span>`;
const doc = (file) => data.documents.find((d) => d.path.split("/").pop() === file);
const stepAttr = (s) => (s === undefined || s === null || s === "" ? "" : ` data-step="${s}"`);
const fmt = (value, digits = 1) => Number(value).toFixed(digits);

// ------------------------------------------------------------------ 1. lib/w04-data.js

write("lib/w04-data.js", `/* Generated by scripts/workshop04/build-deck.mjs from scripts/workshop04/data/w04-data.json
   (data version ${data.meta.dataVersion}, built ${data.meta.builtOn}). Do not edit by hand. */
window.W04_DATA = Object.freeze(${JSON.stringify(data)});
`);

// ------------------------------------------------------------------ 2. generated fragments

function parseRange(spec, max) {
  if (!spec) return [...Array(max).keys()];
  const out = [];
  for (const part of spec.split(",")) {
    const [a, b] = part.split("-").map(Number);
    for (let i = a; i <= (b === undefined ? a : b); i += 1) out.push(i);
  }
  return out;
}

// A document "paper" card rendered from documents[].lines. Params: file, lines (index ranges),
// mark (indices outlined in Mennige), box (indices boxed in ink), id, cls, caption (yes/no).
function genDoc(params) {
  const d = doc(params.file);
  if (!d) throw new Error(`gen:doc unknown file ${params.file}`);
  const base = `documents.${params.file.replace(/\.[a-z]+$/, "")}.lines`;
  const show = parseRange(params.lines, d.lines.length);
  const mark = new Set(params.mark ? parseRange(params.mark) : []);
  const box = new Set(params.box ? parseRange(params.box) : []);
  // Each item is one rendered line; consecutive marked (Mennige) or boxed (ink) lines share one frame.
  const items = [];
  let table = null;
  const flush = () => { if (table) { items.push({ html: `<div class="doc__table">${table.join("")}</div>`, flag: table.flag }); table = null; } };
  for (const i of show) {
    const line = d.lines[i];
    if (line === undefined || /^\|[-| ]+\|$/.test(line)) continue;
    const flag = mark.has(i) ? "mark" : box.has(i) ? "box" : "";
    if (line.startsWith("|")) {
      if (!table || table.flag !== flag) { flush(); table = []; table.flag = flag; }
      const cells = line.split("|").slice(1, -1);
      const head = /^\|[-| ]+\|$/.test(d.lines[i + 1] || "");
      table.push(`<p class="doc__tr${head ? " doc__tr--head" : ""}">${cells.map((_, c) => j(`${base}.${i}`, `cell:${c}`)).join("")}</p>`);
      continue;
    }
    flush();
    let html;
    if (line.trim() === "") html = '<p class="doc__gap" aria-hidden="true"></p>';
    else if (line.startsWith("# ")) html = `<p class="doc__title">${j(`${base}.${i}`, "md")}</p>`;
    else if (/^--- .* ---$/.test(line)) html = `<p class="doc__page">${j(`${base}.${i}`)}</p>`;
    else html = `<p class="doc__line">${j(`${base}.${i}`)}</p>`;
    items.push({ html, flag });
  }
  flush();
  const rows = [];
  for (let k = 0; k < items.length;) {
    const flag = items[k].flag;
    let e = k;
    while (e < items.length && items[e].flag === flag) e += 1;
    const chunk = items.slice(k, e).map((it) => it.html).join("");
    rows.push(flag ? `<div class="doc__${flag}"${flag === "mark" ? " data-focus" : ""}>${chunk}</div>` : chunk);
    k = e;
  }
  const caption = params.caption === "no" ? "" : `<figcaption class="doc__file">${esc(params.file)}</figcaption>`;
  return `<figure class="doc${params.cls ? ` ${params.cls}` : ""}"${params.id ? ` id="${params.id}"` : ""}>${caption}<div class="doc__sheet">${rows.join("")}</div></figure>`;
}

// The location-based waterfall on scene `anatomy`, from waterfall.lb (T7 is 0.0 in LB and not drawn).
function genWaterfall() {
  const steps = data.waterfall.lb.filter((s) => s.step !== "T7");
  const W = 1360, top = 56, bottom = 456, lo = 1400, hi = 2000;
  const y = (v) => top + ((hi - v) / (hi - lo)) * (bottom - top);
  const col = 150, barW = 104, x0 = 40;
  // The right total stays hidden until the prediction vote is over (press 2); a "?" holds its place.
  const reveal = { start: 0, T1: 2, T2: 2, T3: 3, T4: 3, T5: 4, T6: 4, end: 2 };
  const names = { start: ["Raw-folder", "answer"], T1: ["Duplicate", "March"], T2: ["October", "missing"], T3: ["Talbrück", "bill"], T4: ["1.240 MWh", "misread"], T5: ["Gas", "Hs / Hi"], T6: ["AdBlue", "as diesel"], end: ["Right", "total"] };
  const parts = [];
  const cols = [...steps.map((s, i) => ({ ...s, i })), { step: "end", i: steps.length }];
  cols.forEach((c, k) => {
    const x = x0 + k * col;
    const s = reveal[c.step];
    const g = [];
    if (c.step === "start") {
      const yt = y(c.running_t);
      g.push(`<rect class="wf-bar wf-bar--raw" x="${x}" y="${fmt(yt)}" width="${barW}" height="${fmt(bottom - yt)}" data-motion="grow" />`);
      g.push(`<text class="wf-val" x="${x + barW / 2}" y="${fmt(yt - 14)}" text-anchor="middle" data-j="waterfall.lb.start.running_en">${esc(c.running_en)}</text>`);
    } else if (c.step === "end") {
      const last = steps[steps.length - 1];
      const yt = y(last.running_t);
      g.push(`<rect class="wf-bar wf-bar--ink" x="${x}" y="${fmt(yt)}" width="${barW}" height="${fmt(bottom - yt)}" data-motion="grow" />`);
      g.push(`<text class="wf-val wf-val--end" x="${x + barW / 2}" y="${fmt(yt + 40)}" text-anchor="middle" data-num="total_lb_2025" data-form="bare">${esc(fillApi.numberText(data, "total_lb_2025", "bare"))}</text>`);
    } else {
      const prev = steps[c.i - 1].running_t;
      const a = y(Math.max(prev, c.running_t));
      const b = y(Math.min(prev, c.running_t));
      const h = Math.max(3, b - a);
      const up = c.change_t > 0;
      g.push(`<path class="wf-link" d="M${x - col + barW} ${fmt(y(prev))}H${x}" data-motion="draw" />`);
      g.push(`<rect class="wf-bar wf-bar--change" x="${x}" y="${fmt(a)}" width="${barW}" height="${fmt(h)}" data-motion="grow" style="--grow-origin: 50% ${up ? "100%" : "0%"}" />`);
      const ly = up ? a - 14 : a + h + 34;
      g.push(`<text class="wf-val wf-val--change" x="${x + barW / 2}" y="${fmt(ly)}" text-anchor="middle" data-j="waterfall.lb.${c.step}.change_en">${esc(c.change_en)}</text>`);
    }
    const [l1, l2] = names[c.step];
    g.push(`<text class="wf-name" x="${x + barW / 2}" y="${bottom + 34}" text-anchor="middle">${esc(l1)}</text>`);
    g.push(`<text class="wf-name wf-name--sub" x="${x + barW / 2}" y="${bottom + 62}" text-anchor="middle">${esc(l2)}</text>`);
    parts.push(`<g class="wf-col" data-col="${c.step}"${stepAttr(s)}>${g.join("")}</g>`);
    if (c.step === "end") {
      parts.push(`<g class="wf-col wf-col--pending" data-step-until="2"><text class="wf-pending" x="${x + barW / 2}" y="${bottom - 120}" text-anchor="middle">?</text>`
        + `<text class="wf-name" x="${x + barW / 2}" y="${bottom + 34}" text-anchor="middle">${esc(l1)}</text><text class="wf-name wf-name--sub" x="${x + barW / 2}" y="${bottom + 62}" text-anchor="middle">${esc(l2)}</text></g>`);
    }
  });
  // Axis: the baseline carries a break mark, because the bars start at a cut, not at zero.
  const axis = `<path class="wf-axis" d="M${x0 - 24} ${bottom}H${x0 + cols.length * col - (col - barW)}" /><path class="wf-break" d="M${x0 - 30} ${bottom + 10}l10 -20M${x0 - 20} ${bottom + 10}l10 -20" />`;
  // Step 5: the swing band between the lowest and highest running total.
  const yMax = y(data.numbers.wf_lb_max_t.value), yMin = y(data.numbers.wf_lb_min_t.value);
  const bx = x0 + cols.length * col - (col - barW) + 28;
  const band = `<g class="wf-swing" data-step="5" data-focus>`
    + `<path class="wf-swing__line" d="M${x0} ${fmt(yMax)}H${bx}M${x0} ${fmt(yMin)}H${bx}" data-motion="draw" />`
    + `<path class="wf-swing__bracket" d="M${bx} ${fmt(yMax)}h14V${fmt(yMin)}h-14" data-motion="draw" style="--order:1" />`
    + `<text class="wf-swing__label" x="${bx + 26}" y="${fmt(yMax + 10)}" data-num="wf_lb_max_t" data-motion="fade" style="--order:2">${esc(fillApi.numberText(data, "wf_lb_max_t"))}</text>`
    + `<text class="wf-swing__label" x="${bx + 26}" y="${fmt(yMin + 10)}" data-num="wf_lb_min_t" data-motion="fade" style="--order:2">${esc(fillApi.numberText(data, "wf_lb_min_t"))}</text>`
    + `</g>`;
  return `<svg class="wf" id="anatomy-wf" viewBox="0 0 ${W} 530" width="${W}" height="530" role="img" aria-label="Waterfall, location-based Scope 1 and 2: from the raw-folder answer, one correction per bar, to the right total.">${axis}${parts.join("")}${band}</svg>`;
}

// The site × month grid on `month-grid`, from coverage.asDelivered. Step 1 shows the empty grid,
// step 3 the delivered documents, step 5 the October meter reading.
function genGrid() {
  const rows = data.coverage.rows;
  const label = { "WN Strom": ["Werk Nord", "electricity"], "WS Strom": ["Werk Süd", "electricity"], "LO Strom": ["Lager Ost", "electricity"], "WN Gas": ["Werk Nord", "gas"], "WS Gas": ["Werk Süd", "gas"], "FL Diesel": ["Fleet", "diesel"] };
  const months = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"];
  const lx = 0, cx = 330, cw = 76, top = 44, rh = 50, ch = 38;
  const W = cx + 12 * cw + 4;
  const H = top + rows.length * rh + 4;
  const frame = [], fills = [], labels = [];
  months.forEach((m, i) => labels.push(`<text class="mg-month" x="${cx + i * cw + cw / 2}" y="30" text-anchor="middle">${m}</text>`));
  rows.forEach((r, ri) => {
    const yy = top + ri * rh;
    const [a, b] = label[r];
    labels.push(`<text class="mg-row" x="${lx}" y="${yy + 34}"><tspan class="mg-row__site">${esc(a)}</tspan><tspan class="mg-row__carrier" dx="10">${esc(b)}</tspan></text>`);
    for (let i = 0; i < 12; i += 1) frame.push(`<rect class="mg-cell" x="${cx + i * cw + 4}" y="${yy + 7}" width="${cw - 8}" height="${ch}" />`);
    const cells = data.coverage.asDelivered[r];
    let i = 0;
    while (i < 12) {
      const v = cells[i];
      let span = 1;
      while (i + span < 12 && cells[i + span] === v && ["J", "Q", "S"].includes(v)) span += 1;
      if (v === "Q") span = 3;
      const x = cx + i * cw + 4, w = span * cw - 8;
      if (v === "0") {
        fills.push(`<rect class="mg-missing" x="${x}" y="${yy + 7}" width="${w}" height="${ch}" />`);
      } else if (v === "2") {
        fills.push(`<g class="mg-dup" data-focus><rect class="mg-doc-bg" x="${x}" y="${yy + 7}" width="${w}" height="${ch}" /><rect class="mg-doc" x="${x}" y="${yy + 7}" width="${w}" height="${ch}" /><rect class="mg-badge" x="${x + w - 30}" y="${yy + 1}" width="34" height="34" /><text class="mg-badge__t" x="${x + w - 13}" y="${yy + 26}" text-anchor="middle">2</text></g>`);
      } else {
        const tag = v === "J" ? "annual statement" : v === "Q" ? `Q${Math.floor(i / 3) + 1}` : v === "S" ? "one bill" : "";
        fills.push(`<rect class="mg-doc-bg" x="${x}" y="${yy + 7}" width="${w}" height="${ch}" /><rect class="mg-doc${span > 1 ? " mg-doc--span" : ""}" x="${x}" y="${yy + 7}" width="${w}" height="${ch}" />`);
        if (tag) fills.push(`<text class="mg-tag" x="${x + w / 2}" y="${yy + 33}" text-anchor="middle">${tag}</text>`);
      }
      i += span;
    }
  });
  const aug = cx + 7 * cw + cw / 2;
  const octX = cx + 9 * cw + 4;
  const dip = `<path class="mg-dip" d="M${aug - 8} ${top + 7 + ch + 2}l8 9 8-9" />`;
  const meter = `<g class="mg-meter" data-step="5" data-focus><rect x="${octX}" y="${top + 7}" width="${cw - 8}" height="${ch}" data-motion="fade" /><text x="${octX + (cw - 8) / 2}" y="${top + 33}" text-anchor="middle" data-motion="fade">meter</text></g>`;
  return `<svg class="mg" id="month-grid-svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Site by month grid for 2025: which documents cover which months.">`
    + `<g class="mg-frame" data-step="1">${labels.join("")}${frame.join("")}</g>`
    + `<g class="mg-fill" data-step="3">${fills.join("")}${dip}</g>${meter}</svg>`;
}

// A ledger excerpt: the eight columns shown on `the-ledger`.
function genLedger(params) {
  const ids = params.rows.split(",");
  const head = ["row_id", "entity_on_document", "period", "qty_source", "unit_source", "qty_norm", "status", "source (file · quote)"];
  const body = ids.map((id) => {
    const r = data.ledger.find((row) => row.row_id === id);
    if (!r) throw new Error(`gen:ledger unknown row ${id}`);
    const p = `ledger.${id}`;
    const excluded = r.status === "excluded";
    const file = r.source_file.split("/").pop();
    return `<tr class="lg-row${excluded ? " lg-row--excluded" : ""}" data-row="${id}">`
      + `<td class="lg-id">${j(`${p}.row_id`)}</td>`
      + `<td class="lg-entity">${j(`${p}.entity_on_document`)}</td>`
      + `<td class="lg-period">${j(`${p}.period_start`)}<br />${j(`${p}.period_end`)}</td>`
      + `<td class="lg-num">${j(`${p}.qty_source`)}</td>`
      + `<td>${j(`${p}.unit_source`)}</td>`
      + `<td class="lg-num">${j(`${p}.qty_norm`)}</td>`
      + `<td class="lg-status">${j(`${p}.status`)}</td>`
      + `<td class="lg-src"><span class="lg-file">${esc(file)}</span>${j(`${p}.source_quote`, "", "lg-quote")}</td>`
      + `</tr>`;
  }).join("");
  return `<table class="lg" id="${params.id || "ledger"}"><thead><tr>${head.map((h, i) => `<th${i === 1 ? ' class="lg-entity-head" id="the-ledger-entity-head"' : ""}>${esc(h)}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table>`;
}

// The pinned factor table excerpt on `six-rules`.
function genFactors(params) {
  const ids = params.ids.split(",");
  const rows = ids.map((id) => {
    const f = data.factors[id];
    if (!f) throw new Error(`gen:factors unknown ${id}`);
    const digits = id === "F-DSL" ? "fix1" : "fix2";
    return `<tr data-factor="${id}"${id === params.mark ? " class=\"is-mark\"" : ""}><td class="ft-id">${esc(id)}</td><td>${j(`factors.${id}.year`)}</td><td>${j(`factors.${id}.basis`)}</td><td class="ft-num">${j(`factors.${id}.value`, digits)}</td><td class="ft-unit">${j(`factors.${id}.unit`)}</td></tr>`;
  }).join("");
  return `<table class="ft"><thead><tr><th>factor_id</th><th>year</th><th>basis</th><th class="ft-num">value</th><th>unit</th></tr></thead><tbody>${rows}</tbody></table>`;
}

// The stacked bar of 2025 electricity on `two-scope-2`: Werk Süd (covered) and the rest.
function genStack() {
  const W = 1040;
  const total = data.numbers.el_total_kwh.value;
  const ws = data.numbers.el_ws_kwh.value;
  const wsW = Math.round((ws / total) * W);
  return `<div class="st" style="--st-ws:${wsW}px">`
    + `<div class="st__bar"><span class="st__ws" data-motion="grow" data-axis="x"><svg class="icon icon--40" aria-hidden="true"><use href="#i-certificate" /></svg></span><span class="st__rest" data-motion="grow" data-axis="x" style="--order:1"></span></div>`
    + `<p class="st__lab st__lab--ws"><b>Werk Süd ${n("el_ws_mwh")}</b><span>covered by guarantees of origin</span></p>`
    + `<p class="st__lab st__lab--rest"><b>Werk Nord + Lager Ost ${n("el_uncovered_mwh")}</b><span>no certificate</span></p>`
    + `<p class="st__total">2025 electricity ${n("el_total_mwh")} · covered ${n("renewable_share_el_pct")}</p>`
    + `</div>`;
}

// The location-based to market-based bridge on `two-scope-2` (press 5).
function genBridge() {
  const lb = data.numbers.s2lb_2025.value, cert = data.numbers.bridge_cert_t.value, rm = data.numbers.bridge_rm_t.value, mb = data.numbers.s2mb_2025.value;
  const W = 1040, x0 = 300, k = (W - x0 - 150) / lb; // px per t, bars start at 0
  const rows = [
    { label: "Location-based", a: 0, b: lb, cls: "br-bar--lb", key: "s2lb_2025", order: 0 },
    { label: "Certificate, Werk Süd", a: lb + cert, b: lb, cls: "br-bar--minus", key: "bridge_cert_t", order: 1 },
    { label: "Residual mix on the rest", a: lb + cert, b: lb + cert + rm, cls: "br-bar--plus", key: "bridge_rm_t", order: 2 },
    { label: "Market-based", a: 0, b: mb, cls: "br-bar--mb", key: "s2mb_2025", order: 3 },
  ];
  const rh = 64;
  const out = rows.map((r, i) => {
    const yy = i * rh;
    const xa = x0 + Math.min(r.a, r.b) * k, w = Math.abs(r.b - r.a) * k;
    return `<g class="br-row" style="--order:${r.order}"><text class="br-label" x="${x0 - 24}" y="${yy + 34}" text-anchor="end">${esc(r.label)}</text>`
      + `<rect class="br-bar ${r.cls}" x="${fmt(xa)}" y="${yy + 8}" width="${fmt(w)}" height="${rh - 20}" data-motion="grow" data-axis="x" style="--order:${r.order}" />`
      + `<text class="br-val" x="${fmt(xa + w + 16)}" y="${yy + 38}" data-num="${r.key}" data-motion="fade" style="--order:${r.order}">${esc(fillApi.numberText(data, r.key))}</text></g>`;
  }).join("");
  return `<svg class="br" id="two-scope-2-bridge" viewBox="0 0 ${W} ${rows.length * rh}" width="${W}" height="${rows.length * rh}" role="img" aria-label="Bridge from location-based to market-based Scope 2, 2025.">${out}</svg>`;
}

// The 2024 to 2025 bridge on `what-drove-it`, one per method, from drivers.lb / drivers.mb. Bars start
// at a cut (break mark on the baseline), as on `anatomy`. Both charts share one scale and one cut, so
// the certificate bar reads ten times the grid-factor bar, as the numbers say. The frame with both
// totals shows on entry; the change bars and their names appear on press `step` (the driver names
// would answer the room vote). Params: method (lb|mb), step.
function genDrivers(params) {
  const m = params.method;
  const list = data.drivers[m];
  const startKey = `total_${m}_2024`, endKey = `total_${m}_2025`;
  const start = data.numbers[startKey].value, end = data.numbers[endKey].value;
  const keyFor = {
    lb: { grid_factor: "drv_lb_grid_t", less_electricity: "drv_lb_elec_t", less_gas: "drv_lb_gas_t", less_diesel: "drv_lb_diesel_t" },
    mb: { certificates: "drv_mb_cert_t", less_electricity: "drv_mb_elec_t", less_gas_diesel: "drv_mb_s1_t" },
  }[m];
  const names = {
    grid_factor: ["Grid", "factor"], certificates: ["Guarantees", "of origin"], less_electricity: ["Less", "electricity"],
    less_gas: ["Less", "gas"], less_diesel: ["Less", "diesel"], less_gas_diesel: ["Less gas", "and diesel"],
  };
  const W = 820, top = 50, bottom = 300, H = bottom + 66, col = 136, barW = 92, x0 = 22;
  const ends = ["lb", "mb"].map((x) => data.numbers[`total_${x}_2025`].value);
  const starts = ["lb", "mb"].map((x) => data.numbers[`total_${x}_2024`].value);
  const lo = Math.floor((Math.min(...ends) - 40) / 50) * 50, hi = Math.ceil((Math.max(...starts) + 20) / 50) * 50;
  const y = (v) => top + ((hi - v) / (hi - lo)) * (bottom - top);
  const frame = [], bars = [];
  const colX = (k) => x0 + k * col;
  const total = (k, key, cls) => {
    const v = data.numbers[key].value, yt = y(v);
    frame.push(`<rect class="dv-bar ${cls}" x="${colX(k)}" y="${fmt(yt)}" width="${barW}" height="${fmt(bottom - yt)}" />`);
    frame.push(`<text class="dv-val" x="${colX(k) + barW / 2}" y="${fmt(yt - 14)}" text-anchor="middle" data-num="${key}" data-form="bare">${esc(fillApi.numberText(data, key, "bare"))}</text>`);
  };
  total(0, startKey, "dv-bar--prior");
  let running = start;
  list.forEach((d, i) => {
    const k = i + 1, next = running + d.t;
    const a = y(running), b = y(next), h = Math.max(3, b - a);
    const key = keyFor[d.id];
    if (!key) throw new Error(`gen:drivers no number key for ${m}.${d.id}`);
    bars.push(`<path class="dv-link" d="M${colX(k - 1) + barW} ${fmt(a)}H${colX(k)}" data-motion="draw" style="--order:${i}" />`);
    bars.push(`<rect class="dv-bar dv-bar--change${i === 0 ? " dv-bar--lead" : ""}" x="${colX(k)}" y="${fmt(a)}" width="${barW}" height="${fmt(h)}" data-motion="grow" style="--grow-origin: 50% 0%; --order:${i}" />`);
    // On the shared scale the small bars sit close to the baseline: every change value goes above its bar.
    bars.push(`<text class="dv-val dv-val--change" x="${colX(k) + barW / 2}" y="${fmt(a - 12)}" text-anchor="middle" data-num="${key}" data-form="bare" data-motion="fade" style="--order:${i}">${esc(fillApi.numberText(data, key, "bare"))}</text>`);
    running = next;
  });
  const endK = list.length + 1;
  bars.push(`<path class="dv-link" d="M${colX(endK - 1) + barW} ${fmt(y(running))}H${colX(endK)}" data-motion="draw" style="--order:${list.length}" />`);
  total(endK, endKey, "dv-bar--now");
  // Own use: a bracket over every bar after the first (the factor or the certificate).
  const ownKey = `drv_${m}_own_t`;
  const bx1 = colX(2) - 6, bx2 = colX(endK - 1) + barW + 6;
  const by = y(start) - 44;
  bars.push(`<g class="dv-own"><path class="dv-own__bracket" d="M${bx1} ${fmt(by + 14)}V${fmt(by)}H${bx2}V${fmt(by + 14)}" data-motion="draw" style="--order:${list.length}" />`
    + `<text class="dv-own__label" x="${(bx1 + bx2) / 2}" y="${fmt(by - 14)}" text-anchor="middle" data-motion="fade" style="--order:${list.length}">own use <tspan class="dv-own__num" data-num="${ownKey}">${esc(fillApi.numberText(data, ownKey))}</tspan></text></g>`);
  const labels = [];
  const colNames = [["2024", ""], ...list.map((d) => names[d.id]), ["2025", ""]];
  colNames.forEach(([l1, l2], k) => {
    const into = k === 0 || k === endK ? labels : bars;
    into.push(`<text class="dv-name" x="${colX(k) + barW / 2}" y="${bottom + 34}" text-anchor="middle">${esc(l1)}</text>`);
    if (l2) into.push(`<text class="dv-name dv-name--sub" x="${colX(k) + barW / 2}" y="${bottom + 62}" text-anchor="middle">${esc(l2)}</text>`);
  });
  const axis = `<path class="dv-axis" d="M${x0 - 18} ${bottom}H${colX(endK) + barW + 10}" /><path class="dv-break" d="M${x0 - 24} ${bottom + 10}l10 -20M${x0 - 14} ${bottom + 10}l10 -20" />`;
  const label = m === "lb" ? "Location-based Scope 1 and 2, 2024 to 2025" : "Market-based Scope 1 and 2, 2024 to 2025";
  return `<svg class="dv" id="what-drove-it-${m}" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="${attr(label)}: one bar per driver.">`
    + `<g class="dv-frame">${axis}${frame.join("")}${labels.join("")}</g>`
    + `<g class="dv-changes"${stepAttr(params.step)}>${bars.join("")}</g></svg>`;
}

// Both waterfalls as one table on `appendix-arithmetic`: step, location-based change and running
// total, market-based change and running total (waterfall.lb / waterfall.mb, same order T1 to T7).
function genWfTable() {
  const lb = data.waterfall.lb, mb = data.waterfall.mb;
  const names = { start: "Raw-folder answer", T1: "T1 duplicate out", T2: "T2 October in", T3: "T3 Talbrück out", T4: "T4 unit as MWh", T5: "T5 Hs gas factor", T6: "T6 AdBlue out", T7: "T7 residual mix" };
  const rows = lb.map((s, i) => {
    const t = mb[i];
    if (t.step !== s.step) throw new Error("gen:wftable waterfall order differs");
    const c = (w, field) => (w[field] == null ? "" : j(`waterfall.${w === s ? "lb" : "mb"}.${w.step}.${field}`));
    return `<tr><td>${esc(names[s.step])}</td><td class="ax-num">${c(s, "change_en")}</td><td class="ax-num">${c(s, "running_en")}</td><td class="ax-num">${c(t, "change_en")}</td><td class="ax-num">${c(t, "running_en")}</td></tr>`;
  }).join("");
  return `<table class="ax-table ax-wf"><thead><tr><th>Correction, in order</th><th class="ax-num">LB</th><th class="ax-num">running</th><th class="ax-num">MB</th><th class="ax-num">running</th></tr></thead><tbody>${rows}</tbody></table>`;
}

const GENERATORS = { doc: genDoc, waterfall: genWaterfall, grid: genGrid, ledger: genLedger, factors: genFactors, stack: genStack, bridge: genBridge, drivers: genDrivers, wftable: genWfTable };

function parseParams(text) {
  const params = {};
  for (const m of text.matchAll(/(\w+)=("[^"]*"|\S+)/g)) params[m[1]] = m[2].replace(/^"|"$/g, "");
  return params;
}

let html = readFileSync(path.join(DECK, "slides.html"), "utf8");
html = html.replace(/<!-- gen:(\w+)([^>]*?)-->([\s\S]*?)<!-- \/gen:\1 -->/g, (_all, name, rawParams) => {
  const gen = GENERATORS[name];
  if (!gen) { findings.push(`unknown generator gen:${name}`); return _all; }
  return `<!-- gen:${name}${rawParams}-->${gen(parseParams(rawParams))}<!-- /gen:${name} -->`;
});

// ------------------------------------------------------------------ 3. data-num / data-j text

html = html.replace(/(<(\w+)\b([^>]*\bdata-(?:num|j)="[^"]*"[^>]*)>)([^<]*)(<\/\2>)/g, (all, open, _tag, attrs, _text, close) => {
  const get = (name) => (new RegExp(`\\bdata-${name}="([^"]*)"`).exec(attrs) || [])[1];
  const text = fillApi.textFor(data, { num: get("num"), j: get("j") ? get("j").replace(/&quot;/g, '"') : undefined, form: get("form") });
  if (text == null) { findings.push(`unresolved binding: ${get("num") || get("j")}`); return all; }
  return `${open}${esc(text)}${close}`;
});

write("slides.html", html);

// ------------------------------------------------------------------ 4. lint

const numberTokens = new Set();
const normals = (token) => {
  const t = token.replace(/^[+−-]/, "").replace(/%$/, "");
  const out = new Set();
  const en = t.replace(/,/g, "");
  const de = t.replace(/\./g, "").replace(/,/g, ".");
  for (const v of [en, de, t]) {
    const f = Number(v);
    if (Number.isFinite(f)) { out.add(String(f)); out.add(f.toFixed(1)); out.add(f.toFixed(2)); }
  }
  return out;
};
(function walk(value) {
  if (value == null) return;
  if (typeof value === "number") { for (const x of normals(String(value))) numberTokens.add(x); return; }
  if (typeof value === "string") { for (const m of value.matchAll(/\d[\d.,]*/g)) for (const x of normals(m[0].replace(/[.,]$/, ""))) numberTokens.add(x); return; }
  if (Array.isArray(value)) { value.forEach(walk); return; }
  if (typeof value === "object") { Object.entries(value).forEach(([k, v]) => { walk(k); walk(v); }); }
})(data);

// Legal references and thresholds (Directive 2024/825, 2026/470, 1,000 employees, €450m, Scope 3
// categories 13 and 15, § 42 EnWG, § 5 UWG), the canvas, and one rounded vote option ("About 500 t").
const LEGAL = new Set(["825", "470", "1000", "450", "15", "13", "42", "5", "1920", "1080", "500"]);
// Reference facts quoted on the appendix and limits scenes (SPEC §2.4 A2, §2.3 limits, §9), which are
// not case data: Delegated Regulations 2026/1560 and 2026/1563, the 2015 Scope 2 Guidance, the UBA
// grid factor 2022 (433 g CO2/kWh; 386 and 363 are in the factor notes of the dataset) and the two
// published extraction accuracies (ESGReveal 76.9%, ESG Insight 78.2%).
for (const ref of ["1560", "1563", "2015", "433", "76.9", "78.2"]) LEGAL.add(ref);
const visible = html
  .replace(/<script[\s\S]*?<\/script>/g, " ")
  .replace(/<style[\s\S]*?<\/style>/g, " ")
  .replace(/<!--[\s\S]*?-->/g, " ")
  .replace(/<symbol[\s\S]*?<\/symbol>/g, " ")
  .replace(/<(\w+)\b[^>]*\bdata-(?:num|j)="[^"]*"[^>]*>[^<]*<\/\1>/g, " ")
  .replace(/<[^>]+>/g, " ")
  .replace(/&[a-z]+;/g, " ");
for (const m of visible.matchAll(/[+−-]?\d[\d.,]*%?/g)) {
  const token = m[0].replace(/[.,]$/, "");
  const bare = token.replace(/^[+−-]/, "").replace(/%$/, "");
  const v = Number(bare.replace(/,/g, ""));
  if (/^\d+$/.test(bare) && (v <= 31 || (v >= 2020 && v <= 2030))) continue;
  if (LEGAL.has(bare.replace(/,/g, ""))) continue;
  if ([...normals(token)].some((x) => numberTokens.has(x))) continue;
  const at = visible.slice(Math.max(0, m.index - 40), m.index + 40).replace(/\s+/g, " ");
  findings.push(`number not in the dataset: "${token}" near "${at}"`);
}

for (const file of ["slides.html", "presenter.html"]) {
  const text = file === "slides.html" ? html : readFileSync(path.join(DECK, file), "utf8");
  if (/[\u2013\u2014]/.test(text)) findings.push(`${file}: en or em dash`);
}
for (const m of html.matchAll(/<p class="q-card__text"[^>]*>([\s\S]*?)<\/p>/g)) {
  const text = m[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
  if (text !== data.question.en) findings.push(`q-card text differs from question.en: "${text}"`);
}

// ------------------------------------------------------------------ 5. presenter notes

const noteFiles = readdirSync(path.join(HERE, "notes")).filter((f) => f.endsWith(".mjs")).sort();
const notes = {};
for (const f of noteFiles) {
  const mod = await import(pathToFileURL(path.join(HERE, "notes", f)).href);
  for (const [key, value] of Object.entries(mod.default)) {
    if (notes[key]) findings.push(`note key ${key} defined twice`);
    notes[key] = value;
  }
}
const sub = (text) => String(text).replace(/\{(\w+)(?:\|(\w+))?\}/g, (all, key, form) => {
  const t = fillApi.numberText(data, key, form);
  if (t == null) { findings.push(`note placeholder {${key}} not in numbers`); return all; }
  return t;
});
const deep = (value) => (typeof value === "string" ? sub(value) : Array.isArray(value) ? value.map(deep) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([k, v]) => [k, deep(v)])) : value);
const sections = [...html.matchAll(/<section class="slide[^"]*" id="([^"]+)"([^>]*)>/g)].map((m) => ({ id: m[1], attrs: m[2] }));
const ordered = {};
for (const s of sections) {
  const key = (/data-note-key="([^"]+)"/.exec(s.attrs) || [])[1] || s.id;
  const seconds = Number((/data-seconds="(\d+)"/.exec(s.attrs) || [])[1] || 0);
  if (!notes[key]) { findings.push(`scene ${s.id} has no presenter notes (key ${key})`); continue; }
  const note = deep(notes[key]);
  for (const field of ["say", "sayAt", "ask", "expectedAudience", "revealOrder", "cut", "appendixRoutes"]) {
    if (!(field in note)) findings.push(`notes ${key}: missing ${field}`);
  }
  const stepMax = Math.max(0, ...[...html.slice(html.indexOf(`id="${s.id}"`)).split(/<section class="slide/)[0].matchAll(/data-step(?:-until)?="(\d+)"/g)].map((m, i, all) => (m[0].includes("until") ? Number(m[1]) - 1 : Number(m[1]))));
  if (note.revealOrder && note.revealOrder.length !== stepMax + 1) findings.push(`notes ${key}: revealOrder has ${note.revealOrder.length} entries, scene has ${stepMax + 1} states`);
  if (/[\u2013\u2014]/.test(JSON.stringify(note))) findings.push(`notes ${key}: en or em dash`);
  ordered[key] = { ...note, clock: { ...(note.clock || {}), budget_seconds: seconds } };
}
for (const key of Object.keys(notes)) if (!ordered[key]) findings.push(`notes ${key}: no scene uses this key`);

write("lib/presenter-notes.js", `/* Generated by scripts/workshop04/build-deck.mjs from scripts/workshop04/notes/*.mjs; {key}
   placeholders are filled from numbers in w04-data.json, so spoken numbers match the slides.
   Do not edit by hand. Read by lib/presenter.js (say, sayAt, ask, expectedAudience, revealOrder,
   cut, appendixRoutes); clock, mode and purpose are documentary. */
window.FOLDLINE_PRESENTER_NOTES = Object.freeze(${JSON.stringify(ordered, null, 2)});
`);

// ------------------------------------------------------------------ report

for (const f of findings) console.error(`lint: ${f}`);
if (CHECK && changed.length) console.error(`out of date: ${changed.join(", ")}`);
console.log(`${CHECK ? "checked" : "built"}: ${sections.length} scenes, ${Object.keys(ordered).length} note entries, ${changed.length} file(s) ${CHECK ? "out of date" : "written"}, ${findings.length} finding(s)`);
process.exit(findings.length || (CHECK && changed.length) ? 1 : 0);
