// ─── Local deterministic course responses ────────
//
// Deterministic local responses for the Claude course widgets, adapted from
// the legacy course demo. The copy is explicit about missing source data and
// avoids implying a model or network request. Each caller invokes a typed,
// same-process function rather than a fetch boundary.
//
// No network call anywhere in this file.

import type { Locale } from "@/lib/i18n/locale";

function hash(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = (h << 5) - h + str.charCodeAt(i);
    h |= 0;
  }
  return h;
}

function clamp01(n: number): number {
  return Math.max(0.06, Math.min(0.94, n));
}

// ─── Generic prompt completion (PromptSandbox, PromptCompare) ──────

/**
 * A deterministic teaching example for a raw prompt. This is not a model
 * completion and must be presented as a local simulation by callers.
 */
export function genericAnswer(prompt: string, locale: Locale = "en"): string {
  const p = prompt.toLowerCase();
  const german = locale === "de";

  if (
    /launch email|announc|rollout|release email|ankündig|einführung|e-mail/.test(
      p,
    )
  ) {
    const structured =
      /constraints|format|audience|context|role/.test(p) || prompt.length > 240;
    if (structured) {
      if (german) {
        return `Betreff: Authentifizierungsumstellung: Aktion erforderlich

Wir ersetzen [bisheriges System] durch [neues System]. Das Migrationsfenster läuft vom [Startdatum] bis [Enddatum]. Die verpflichtende Umstellung erfolgt am [Datum].

Aktion: Stelle deinen Dienst anhand des freigegebenen Runbooks um und führe die dokumentierte Prüfung aus.

Rollback-Kriterium: [messbares Kriterium aus dem Rollout-Plan].

Support: [Kanal oder Kontakt]. Runbook: [Link].

Ersetze die Platzhalter vor dem Versand mit Angaben aus dem freigegebenen Rollout-Plan.`;
      }
      return `Subject: Authentication migration: action required

We are replacing [current system] with [new system]. The migration window runs from [start date] to [end date]. Mandatory cutover is [date].

Action: migrate your service using the approved runbook and run the documented check.

Rollback criterion: [measurable criterion from the rollout plan].

Support: [channel or contact]. Runbook: [link].

Replace every placeholder with approved rollout data before sending.`;
    }
    if (german) {
      return `Betreff: Neuer Authentifizierungsdienst

Wir führen einen neuen Authentifizierungsdienst ein. Details zu Zeitplan, Migration und Support fehlen in diesem Prompt. Ergänze diese Angaben, bevor du den Text verwendest.`;
    }
    return `Subject: Authentication service change

The prompt does not provide the migration window, required action, cutover date, rollback criteria, or support route. Add those facts from the approved rollout plan before drafting the announcement.`;
  }

  if (/p99|latency|microservice|observability|which.*service/.test(p)) {
    if (german) {
      return `Beispiel für eine unbelegte Antwort: „checkout-service hat die höchste p99-Latenz.“

Diese lokale Simulation hat keine Telemetriedaten und ruft Claude nicht auf. Ein realer Ablauf muss gemessene p99-Werte anfordern oder ein lesendes Metrik-Tool verwenden und die Aussage damit belegen.`;
    }
    return `Illustrative unsupported answer: "checkout-service has the highest p99."

This local simulation has no telemetry and does not call Claude. A real workflow should request measured p99 values or use a read-only metrics tool, then cite the result.`;
  }

  if (
    /oncall|on-call|rotation|owns|who (owns|manages)|zuständig|verantwort/.test(
      p,
    )
  ) {
    if (german) {
      return `Beispiel für eine unbelegte Antwort: „Das Identity-Team ist zuständig.“

Diese lokale Simulation hat keinen Dienstkatalog oder Bereitschaftsplan und ruft Claude nicht auf. Stelle die aktuelle Quelle bereit, bevor du eine Zuständigkeit übernimmst.`;
    }
    return `Illustrative unsupported answer: "the identity team owns it."

This local simulation has no service catalog or on-call data and does not call Claude. Supply the current source before accepting an ownership claim.`;
  }

  if (german) {
    return `Dies ist eine feste lokale Antwort aus Kursregeln, keine Claude-Ausgabe.

Stelle für eine reale Aufgabe das benötigte Quellenmaterial bereit und prüfe wesentliche Aussagen daran.`;
  }
  return `This is a fixed local response generated by course rules, not Claude.

For a real task, provide the source material required by the prompt and verify material claims against it.`;
}

// ─── Prompt grading (PromptGrader) ──────────────────────────────────

export interface GraderResult {
  readonly score: number;
  readonly strengths: readonly string[];
  readonly weaknesses: readonly string[];
  readonly oneBetterRewrite: string;
}

/**
 * Deterministic rubric grading, ported from claude-demo.js's `graderJSON`.
 * The grading heuristic only inspects the submitted prompt text itself (the
 * source's `task` variable was only ever interpolated into the LIVE system
 * prompt sent upstream, never read by the grading regexes) so there is no
 * `task` parameter here.
 */
export function gradePrompt(
  userPrompt: string,
  locale: Locale = "en",
): GraderResult {
  const lower = userPrompt.toLowerCase();
  const german = locale === "de";
  const has = (re: RegExp) => re.test(lower);
  const strengths: string[] = [];
  const weaknesses: string[] = [];
  let score = 30;

  if (has(german ? /du bist|du prüfst|als .+|rolle/ : /you are|act as|role/)) {
    score += 14;
    strengths.push(
      german
        ? "Die lokale Regel hat eine Rolle oder Prüfperspektive erkannt."
        : "The local rule detected a role or review perspective.",
    );
  } else {
    weaknesses.push(
      german
        ? "Die lokale Regel hat keine ausdrückliche Rolle oder Prüfperspektive erkannt."
        : "The local rule found no explicit role or review perspective.",
    );
  }
  if (
    has(
      german
        ? /kontext|hintergrund|wir |weil|da /
        : /context|background|we're|because/,
    )
  ) {
    score += 14;
    strengths.push(
      german
        ? "Die lokale Regel hat einen Kontextmarker erkannt; prüfe, ob die nötigen Fakten enthalten sind."
        : "The local rule detected a context marker; verify that it contains the required facts.",
    );
  } else {
    weaknesses.push(
      german
        ? "Die lokale Regel hat keinen ausdrücklichen Kontextmarker erkannt."
        : "The local rule found no explicit context marker.",
    );
  }
  if (
    has(
      german
        ? /format|json|stichpunkt|abschnitt|höchstens \d|wörter|schritte/
        : /format|json|bullet|section|under \d|words|steps/,
    )
  ) {
    score += 16;
    strengths.push(
      german
        ? "Die lokale Regel hat eine prüfbare Formatvorgabe erkannt."
        : "The local rule detected a checkable format marker.",
    );
  } else {
    weaknesses.push(
      german
        ? "Die lokale Regel hat keine ausdrückliche Formatvorgabe erkannt."
        : "The local rule found no explicit format marker.",
    );
  }
  if (userPrompt.length > 220) {
    score += 14;
    strengths.push(
      german
        ? "Der Prompt enthält zusätzliche Angaben; ihre Relevanz muss weiterhin geprüft werden."
        : "Includes additional detail; its relevance still needs review.",
    );
  } else if (userPrompt.length < 80) {
    weaknesses.push(
      german
        ? "Der Prompt ist kurz; konkrete Angaben würden die Aufgabe eingrenzen."
        : "Quite short; more specificity would sharpen the result.",
    );
  }
  if (has(german ? /beispiel|z\.\s?b\./ : /example|e\.g\.|for instance/)) {
    score += 10;
    strengths.push(
      german
        ? "Die lokale Regel hat einen Beispielmarker erkannt; prüfe Freigabe und Repräsentativität."
        : "The local rule detected an example marker; verify approval and representativeness.",
    );
  }

  score = Math.max(8, Math.min(96, score));
  if (strengths.length === 0) {
    strengths.push(
      german
        ? "Die grundlegende Absicht ist erkennbar."
        : "Gets the basic intent across.",
    );
  }
  if (weaknesses.length === 0) {
    weaknesses.push(
      german
        ? "Ein konkretes Beispiel könnte die erwartete Form weiter eingrenzen."
        : "Could add one reviewed example to clarify the expected style.",
    );
  }

  const rewrite = german
    ? `Bearbeite diese Aufgabe anhand der folgenden Spezifikation.

KONTEXT
<notwendiger Hintergrund>

AUFGABE
${(userPrompt.split("\n")[0] || "Bearbeite die Aufgabe").slice(0, 120)}

VORGABEN
- Formuliere konkret.
- Kennzeichne Annahmen, statt fehlende Fakten zu erraten.

FORMAT
<genaue Form der erwarteten Ausgabe>`
    : `Complete this task using the following specification.

CONTEXT
<the background the model needs>

TASK
${(userPrompt.split("\n")[0] || "Do the task").slice(0, 120)}

CONSTRAINTS
- Be specific and concrete.
- State assumptions instead of guessing.

FORMAT
<the exact shape you want back>`;

  return {
    score,
    strengths: strengths.slice(0, 4),
    weaknesses: weaknesses.slice(0, 4),
    oneBetterRewrite: rewrite,
  };
}

// ─── Rewrite arena judging (RewriteArena) ───────────────────────────

export type ArenaWinner = "user" | "original" | "tie";

export interface ArenaResult {
  readonly winner: ArenaWinner;
  readonly why: string;
  readonly userScore: number;
  readonly originalScore: number;
}

/** Deterministic rewrite-vs-original structure comparison. */
export function judgeRewrite(
  original: string,
  rewrite: string,
  locale: Locale = "en",
): ArenaResult {
  const r = rewrite.toLowerCase();
  const german = locale === "de";
  let userScore = 45;
  if ((german ? /du bist|als .+|rolle/ : /you are|role|act as/).test(r))
    userScore += 14;
  if ((german ? /kontext|hintergrund/ : /context|background/).test(r))
    userScore += 12;
  if (
    (german
      ? /format|json|stichpunkt|abschnitt|höchstens \d|schritte/
      : /format|json|bullet|section|under \d|steps/
    ).test(r)
  )
    userScore += 14;
  if (rewrite.length > original.length + 60) userScore += 10;
  if ((german ? /beispiel|z\.\s?b\./ : /example|e\.g\./).test(r))
    userScore += 8;
  userScore = Math.max(20, Math.min(95, userScore));

  const originalScore = Math.max(
    8,
    Math.min(40, 18 + (original.length > 120 ? 10 : 0)),
  );
  const winner: ArenaWinner =
    userScore > originalScore + 4
      ? "user"
      : userScore < originalScore - 4
        ? "original"
        : "tie";
  const why = german
    ? winner === "user"
      ? "Die Überarbeitung ergänzt Rolle, Kontext und Ausgabeformat. Dadurch bleiben weniger Angaben offen."
      : winner === "tie"
        ? "Beide Fassungen benennen die Absicht, legen das Ausgabeformat aber nicht vollständig fest."
        : "Das Original ist hier konkreter; in der Überarbeitung fehlen notwendige Angaben."
    : winner === "user"
      ? "Your rewrite adds role, context, and an explicit output shape, so there is far less for the model to guess."
      : winner === "tie"
        ? "Both convey the intent, but neither fully pins down the output format, which is the deciding gap."
        : "The original is more concrete here; your rewrite drops some specifics it needs.";

  return { winner, why, userScore, originalScore };
}

// ─── Fixed coaching feedback (FillBlank, PromptLibraryShaper) ──────

/** Fixed local feedback for the fill-blank exercise. */
export function fillBlankFeedback(locale: Locale = "en"): string {
  return locale === "de"
    ? "Die Grundstruktur und die Absicht sind erkennbar. Ergänze messbare Erfolgskriterien und ein konkretes Ausgabeformat, damit weniger Interpretationsspielraum bleibt."
    : "The basic structure and intent are clear. Add measurable success criteria and a concrete output format to reduce ambiguity.";
}

/** Fixed local feedback for the shareability exercise. */
export function shareabilityFeedback(locale: Locale = "en"): string {
  return locale === "de"
    ? "Ersetze feste Repository-, Personen- und Kanalnamen durch <PLATZHALTER>. Ergänze oben einen kurzen Einsatzhinweis, damit Teammitglieder den Prompt korrekt einordnen können."
    : "Replace fixed repository, teammate, and channel names with <PLACEHOLDERS>. Add a one-line use note so teammates can apply the prompt in the right context.";
}

// ─── Socratic tutor (SocraticTutor) ─────────────────────────────────

const OPENERS = [
  "Separate supplied context from external retrieval.",
  "State the evidence boundary.",
  "Test the claim against the available source.",
  "Identify what the current context contains.",
] as const;

const QUESTIONS = [
  "If the fact is absent from the context, which authorized source or retrieval tool could supply it?",
  "Which source would support the claim, and how would you verify the cited passage?",
  "Which failure mode applies when an output states an unsupported fact, and which control addresses it?",
  "If role and context were removed, which requirements would become underspecified?",
] as const;

const OPENERS_DE = [
  "Trenne bereitgestellten Kontext von externem Retrieval.",
  "Benenne die Beleggrenze.",
  "Prüfe die Aussage an der verfügbaren Quelle.",
  "Bestimme, was der aktuelle Kontext enthält.",
] as const;

const QUESTIONS_DE = [
  "Wenn die Tatsache im Kontext fehlt: Welche freigegebene Quelle oder welches Retrieval-Tool kann sie liefern?",
  "Welche Quelle würde die Aussage stützen, und wie prüfst du die zitierte Passage?",
  "Welches Fehlerbild liegt vor, wenn eine Ausgabe eine unbelegte Tatsache nennt, und welche Kontrolle wirkt dagegen?",
  "Welche Anforderungen wären ohne Rolle und Kontext nicht mehr eindeutig?",
] as const;

/**
 * A brief reply plus a probing question back, ported from claude-demo.js's
 * `socraticReply`. `turnCount` is the number of user turns sent so far
 * (including this one).
 */
export function socraticReply(
  lastUserMessage: string,
  turnCount: number,
  locale: Locale = "en",
): string {
  const openers = locale === "de" ? OPENERS_DE : OPENERS;
  const questions = locale === "de" ? QUESTIONS_DE : QUESTIONS;
  const opener = openers[Math.abs(hash(lastUserMessage)) % openers.length];
  if (turnCount >= 3) {
    return locale === "de"
      ? `${opener} Claude erzeugt Fortsetzungen aus dem aktuellen Kontextfenster. Verlässliche Ergebnisse benötigen deshalb relevante Quellen, klare Vorgaben und eine Prüfung. Übertrage das jetzt auf einen eigenen Prompt.`
      : `${opener} Claude generates continuations from the current context window. Reliable results therefore need relevant sources, clear constraints, and verification. Apply that to one of your own prompts.`;
  }
  const question =
    questions[
      Math.abs(hash(lastUserMessage + String(turnCount))) % questions.length
    ];
  return locale === "de"
    ? `${opener} Kurzfassung: Claude setzt Text anhand des aktuellen Kontexts fort; Claude ruft dabei nicht automatisch Projektwissen ab. ${question}`
    : `${opener} In short: Claude continues text from the current context; it does not automatically retrieve project knowledge. ${question}`;
}

// ─── CLAUDE.md builder (ClaudeMdBuilder) ────────────────────────────

export interface ClaudeMdFields {
  readonly project: string;
  readonly stack: string;
  readonly conventions: string;
  readonly avoid: string;
  readonly commands: string;
}

/**
 * Generates a local CLAUDE.md draft from typed fields. Callers must present
 * it as a draft and keep secrets out of the input.
 */
export function buildClaudeMd(
  fields: ClaudeMdFields,
  locale: Locale = "en",
): string {
  const german = locale === "de";
  const project =
    fields.project.trim() || (german ? "Dein Projekt" : "Your project");
  const stack =
    fields.stack.trim() ||
    (german
      ? "Sprache, Framework, wichtige Tools"
      : "language, framework, key tools");
  const conventions =
    fields.conventions.trim() || (german ? "Teamregeln" : "house style");
  const avoid =
    fields.avoid.trim() ||
    (german ? "bekannte problematische Muster" : "known anti-patterns");
  const commands = fields.commands.trim() || "build / test / lint";
  if (german) {
    return `# CLAUDE.md

## Projekt
${project}

## Stack
${stack}

## Regeln
- ${conventions}
- Änderungen klein und auf ein Thema begrenzt halten.
- Tests zusammen mit dem Code schreiben.

## Vermeiden
- ${avoid}
- Keine neue Abhängigkeit ohne dokumentierte Begründung.

## Befehle
\`\`\`
${commands}
\`\`\`

## Arbeitsweise
- Präzise und übersichtlich formulieren. Mit dem Ergebnis beginnen.
- Bei Unklarheiten die Annahme nennen, statt still zu raten.`;
  }
  return `# CLAUDE.md

## Project
${project}

## Stack
${stack}

## Conventions
- ${conventions}
- Keep changes small and focused; one concern per change.
- Write tests alongside code.

## Avoid
- ${avoid}
- No new dependencies without a clear reason.

## Commands
\`\`\`
${commands}
\`\`\`

## Working style
- Be crisp and skimmable. Lead with the answer.
- When something is ambiguous, state your assumption instead of guessing silently.`;
}

// ─── Simulated latency (RunConsole "streaming" feel) ────────────────

/**
 * A short, deterministic-in-tests-friendly delay so the console UI can show
 * a loading state, mirroring the source's `wait()` helper. Callers pass a
 * seed (usually the prompt text) so the delay is stable per input rather
 * than genuinely random; tests can stub `Math.random`-free by keeping
 * delays short (under 40ms).
 */
export function simulatedDelayMs(seed: string): number {
  return 12 + (Math.abs(hash(seed)) % 20);
}

export { clamp01 };
