// Presenter notes for Workshop 04, acts 0 to 3 (cover to two-scope-2). Source: SPEC.md §2.3.
// {key} and {key|form} are replaced with numbers[key] from w04-data.json by build-deck.mjs
// (forms: bare, abs, absunit, de), so every spoken number matches the slide.
// revealOrder has one line per state of the scene (state 0 = on entry), matching its data-step range.

export default {
  cover: {
    purpose: "Open with the question; the clock starts on the first press.",
    mode: "listen",
    clock: { start: "00:00", end: "00:40" },
    say: [
      "Presenter cue: the clock starts on your first press.",
      "Today we ask one question about one fictional company, until the end.",
      "Your bank or biggest customer sends it every spring. By the end you will know why the first answer looked right and which parts were wrong.",
    ],
    sayAt: { 0: [0], 1: [0], 2: [0] },
    ask: [],
    expectedAudience: [],
    revealOrder: ["Title, date, question, footer"],
    cut: "Read the question once and advance.",
    appendixRoutes: [],
  },

  host: {
    purpose: "Who is talking; no real company data.",
    mode: "listen",
    clock: { start: "00:40", end: "01:10" },
    say: [
      "I build the data pipelines behind reports like this one.",
      "The company is fictional and the factors are simple teaching values, not official ones, so you can check every number with a phone calculator.",
    ],
    sayAt: { 0: [0], 1: [0] },
    ask: [],
    expectedAudience: [],
    revealOrder: ["Host card and the data line"],
    cut: "Say the data line only, on the-case.",
    appendixRoutes: [],
  },

  "the-case": {
    purpose: "Kellbrunn, its boundary and who asks; stress the second half of the question.",
    mode: "listen",
    clock: { start: "01:10", end: "02:50" },
    say: [
      "Kellbrunn has {staff|bare} people and has never been under the EU reporting law. Since 18 March 2026 that law covers companies with more than 1,000 employees and more than 450 million euros turnover. National law must follow by 19 March 2027.",
      "The bank and the car maker still want this number, and whether it went down.",
      "On press 2: remember the second half of the question. Most of today's trouble is there.",
      "If asked about customer requests: under Directive 2026/470, suppliers with up to 1,000 employees may refuse requests beyond the voluntary standard; Germany must transpose it by 19 March 2027. Details: appendix A4, items 3 and 4.",
    ],
    sayAt: { 0: [0], 1: [1], 2: [2], 3: [1] },
    ask: [],
    expectedAudience: ["Some think the CSRD covers them; answer with the two thresholds."],
    revealOrder: ["Question card, fact strip, boundary sketch", "Three sender cards", "Underline on 'did they go down'"],
    cut: "Skip the sender cards; say 'bank and customers ask'.",
    appendixRoutes: ["appendix-regulation"],
  },

  "the-arc": {
    purpose: "Same AI twice; only the data changes.",
    mode: "listen",
    clock: { start: "02:50", end: "04:00" },
    say: [
      "We ask the AI twice: first on the folder as Kellbrunn has it today, then on the same information prepared as one table with written rules.",
      "The model stays the same, so any difference comes from the preparation. Both answers today are constructed from documented failure modes; recorded runs go into appendix A3.",
    ],
    sayAt: { 0: [0], 1: [1] },
    ask: [],
    expectedAudience: [],
    revealOrder: ["The two-lane drawing and its line", "Route stations"],
    cut: "Show the drawing; skip the second sentence.",
    appendixRoutes: [],
  },

  "raw-folder": {
    purpose: "What the AI gets: a normal folder where twelve bills look like a full year.",
    mode: "listen",
    clock: { start: "04:00", end: "06:30" },
    say: [
      "A normal folder: monthly utility bills, an annual statement, quarterly landlord statements and a fuel-card export.",
      "On press 2: twelve bills for Werk Nord. That looks like a full year.",
      "The AI gets all of it, plus last year's figures and a table of emission factors.",
    ],
    sayAt: { 0: [0], 1: [1], 2: [1] },
    ask: [{ at: 0, text: "Where does your company's electricity number come from today?", aloud: true }],
    expectedAudience: ["Many do not know which file their number comes from."],
    revealOrder: ["Folder tree collapsed, two bill cards", "Folders expanded with counts", "Box around the 12"],
    cut: "Skip the aloud question.",
    appendixRoutes: [],
  },

  "raw-answer": {
    purpose: "The room judges a plausible answer before knowing what is wrong.",
    mode: "vote",
    clock: { start: "06:30", end: "11:30" },
    say: [
      "Must say: This answer is constructed from documented failure modes. It shows the answer when all seven traps fire: six data traps and the market-based method error. It is not a recorded run.",
      "On press 1: read the total and the {wrong_chg_lb_pct|abs}. Do not read the rest aloud.",
      "On press 2: down {wrong_chg_lb_pct|abs}, a normal per-head figure, twelve bills for twelve months, and it shows its sums.",
      "On press 3: hands up. Who would send this to the bank today? Remember your hand; we come back to it at the end.",
    ],
    sayAt: { 0: [0], 1: [1], 2: [2], 3: [3] },
    ask: [{ at: 3, text: "Send this to the bank?", options: ["Send", "Ask back first", "Refuse"], expected: "Most send or ask back; few refuse." }],
    expectedAudience: ["Most pick Send or Ask back first. Those who say Refuse usually cannot name why yet; ask them to hold it."],
    revealOrder: ["Question card, empty answer lane", "Answer text and constructed label", "Five sanity checks", "Room vote"],
    cut: "Skip press 2; go straight to the vote.",
    appendixRoutes: ["appendix-run-record"],
  },

  "month-grid": {
    purpose: "Twelve files are not twelve months: fill the site-by-month grid before adding up.",
    mode: "vote",
    clock: { start: "11:30", end: "16:30" },
    say: [
      "Twelve files are not twelve months.",
      "On press 3: March is in twice; purchasing forwarded the invoice and someone scanned it again. October is missing. One bill covers November and December, so the count still comes to twelve.",
      "On press 3, then ask: August is low. Error or real? Real: the plant holiday. A good assistant flags it and a person confirms it; it never 'corrects' a true value.",
      "On press 5: the facility manager's meter file has October: {oct_kwh|bare} kilowatt hours.",
      "On press 6: the duplicate and the gap almost cancel. Werk Nord is only {wn_net_raw_vs_right_kwh|abs} kilowatt hours off, so nobody notices.",
    ],
    sayAt: { 0: [0], 1: [3], 2: [3], 3: [5], 4: [6] },
    ask: [
      { at: 2, text: "How many months does the Werk Nord folder cover?", options: ["12", "11", "Can't tell from the file count"], expected: "Split between 12 and can't tell." },
      { at: 3, text: "August is {aug_kwh}. Error or real?", aloud: true },
    ],
    expectedAudience: ["Many say 12. On August some say error; answer: plant holiday, flag and confirm."],
    revealOrder: ["Werk Nord folder: 12 files", "Empty grid", "Room vote", "Grid as delivered, August dip", "Both March bills, invoice numbers marked", "Meter rows and the October subtraction", "Net line: duplicate March, missing October, {wn_net_raw_vs_right_kwh} off"],
    cut: "Skip press 4 and the August question.",
    appendixRoutes: [],
  },

  "one-unit": {
    purpose: "A dot that means a thousand, and two checks that catch it.",
    mode: "vote",
    clock: { start: "16:30", end: "20:15" },
    say: [
      "On a German bill the dot separates thousands: one thousand two hundred forty megawatt hours.",
      "On press 3: A and B are the same reading, both a thousand times too small. Kellbrunn's second-largest electricity user almost disappears: minus {unit_lb_t|abs} tonnes.",
      "On press 4: two checks catch it without knowing the format. {ws_misread_kwh_per_employee|bare} kilowatt hours per person would not run one CNC machine for an afternoon, and last year's figure is on the same page.",
      "The fix: keep value and unit as printed and let a written rule convert them.",
    ],
    sayAt: { 0: [0], 1: [2], 2: [3], 3: [4] },
    ask: [{ at: 1, text: "What does '1.240 MWh' mean?", options: ["1.24 MWh", "1,240 kWh", "1,240 MWh = 1,240,000 kWh"], expected: "Mostly C; a few A from people used to English decimals." }],
    expectedAudience: ["Readers of English-format reports pick A."],
    revealOrder: ["Statement card, three options", "Room vote", "Answer C", "Effect bar {unit_lb_t}", "Plausibility line and prior year"],
    cut: "Skip press 4; say the plausibility check in one sentence.",
    appendixRoutes: [],
  },

  "whose-bill": {
    purpose: "The name on the document, checked against a boundary written before the run.",
    mode: "vote",
    clock: { start: "20:15", end: "23:15" },
    say: [
      "Under operational control, which Kellbrunn chose, this bill is out: the partner runs the plant, and contract and meter are Talbrück's.",
      "Forty percent would be right only under the equity-share approach, and that choice is written down before anyone opens the folder.",
      "The row stays in the ledger as excluded, with the reason. It is a later candidate for Scope 3 category 15.",
      "The AI can flag a company name that is not on your list. Whether it is inside the boundary was decided before the run.",
      "If asked about Scope 3: if Kellbrunn rents Halle 3 to Talbrück, check category 13 (downstream leased assets) too. Either way it is Scope 3, not Scope 1 or 2.",
    ],
    sayAt: { 0: [2], 1: [2], 2: [3], 3: [3], 4: [3] },
    ask: [{ at: 1, text: "Whose bill is this?", options: ["Include 100%", "Include 40%", "Leave it out and note it"], expected: "Split between 40% and leave out." }],
    expectedAudience: ["Finance people often pick 40% by analogy with consolidation."],
    revealOrder: ["Bill card, addressee highlighted", "Room vote", "Answer and boundary line", "Effect {jv_lb_t} / {jv_rm_t}"],
    cut: "Skip the effect line.",
    appendixRoutes: [],
  },

  anatomy: {
    purpose: "A small gap in the total can hide large errors in the parts.",
    mode: "vote",
    clock: { start: "23:15", end: "27:30" },
    say: [
      "On press 1: take the hands before any bar moves. The right total stays a question mark until the vote is done.",
      "On press 2: the duplicate and the missing October cancel to {pair_dup_oct_t|abs} tonnes.",
      "On press 3: the Talbrück bill hides four fifths of the unit error.",
      "On press 4: the two small ones. The gas bill states its basis on page 2, and AdBlue is not a fuel.",
      "On press 5: the total swings between {wf_lb_min_t|bare} and {wf_lb_max_t|bare} tonnes on the way. Next year the same errors can add up instead of cancelling.",
      "Six errors, and the total is {gap_lb_t|bare} tonnes off: {gap_lb_pct}. No check on the total would catch that.",
    ],
    sayAt: { 0: [1], 1: [2], 2: [3], 3: [4], 4: [5], 5: [5] },
    ask: [{ at: 1, text: "How far is the AI's total from the right one?", options: ["Less than 5%", "About 10%", "More than 20%"], expected: "Most say about 10% or more." }],
    expectedAudience: ["Most expect a large gap; the {gap_lb_pct} surprises."],
    revealOrder: ["Prediction band, raw-folder bar; right total is a question mark", "Room vote", "Duplicate and October bars, right total", "Talbrück and unit bars", "Gas and AdBlue bars, two cards", "Swing band; title gives the gap"],
    cut: "Skip press 4; mention gas and AdBlue in one sentence.",
    appendixRoutes: ["appendix-arithmetic"],
  },

  "the-ledger": {
    purpose: "One row per quantity, excluded rows kept with a reason; the room completes three rows.",
    mode: "do",
    clock: { start: "27:30", end: "34:00" },
    say: [
      "We hold the question, the model, the prompt and the factor table constant, and change only how the data arrives.",
      "On press 1: a ledger has one row per quantity on a document. Excluded rows stay in with a reason, so anyone sees what was left out.",
      "On press 3: ask which column would have caught the Talbrück bill.",
      "On press 4: this row is done for you.",
      "On press 5: fill the middle row with me. Kilowatt hours? Which factor for location-based, which for market-based?",
      "On press 6: October, alone. Where does the number come from? Which grade, and why B?",
      "On press 7: the control total. Every kilowatt hour on paper is in, out with a reason, or added from the meter, so nothing is lost or counted twice without a row saying so.",
    ],
    sayAt: { 0: [0], 1: [1], 2: [3], 3: [4], 4: [5], 5: [6], 6: [7] },
    ask: [
      { at: 3, text: "Which column would have caught the Talbrück bill?", aloud: true },
      { at: 5, text: "Werk Süd row: kWh? location-based factor? market-based factor?", aloud: true },
      { at: 6, text: "October row: source, quantity, status, grade?", aloud: true },
    ],
    expectedAudience: [
      "Someone says 'multiply by 1,000'; ask them to name the rule and where it is written.",
      "Someone says grade A; answer: a meter reading is not a bill, so B.",
    ],
    revealOrder: [
      "Same and changed columns",
      "Ledger columns, three excluded rows",
      "E-WN-01 evidence expanded",
      "Call-out: which column (answer: Company on the bill, entity_on_document)",
      "Three completion rows; worked row E-WN-03",
      "Half-filled row E-WS-01: room calls out kWh and both factors",
      "E-WS-01 filled; blank row E-WN-10: room calls out source, kWh, status, grade",
      "E-WN-10 filled; control total",
    ],
    cut: "Skip presses 2 and 7; keep the three completion rows.",
    appendixRoutes: ["appendix-arithmetic"],
  },

  "six-rules": {
    purpose: "Six rules a controller would sign, three roles, a pinned factor table.",
    mode: "vote",
    clock: { start: "34:00", end: "38:30" },
    say: [
      "The rules are plain sentences a controller would sign. Each catches one of the traps we just saw.",
      "On press 2: three roles. The reader copies what is printed, with the quote. The clerk applies the rules in a spreadsheet, never in its head. The writer drafts sentences and cites rows. The AI may propose rules; a spreadsheet applies them and a person approves the list.",
      "On press 4: for a comparison the factor rule matters most. The AI picks an ID from our table and records the edition. Last year's factor looks almost the same and would wipe out the whole grid effect we are about to find.",
      "If asked about real factors: appendix A2.",
    ],
    sayAt: { 0: [0], 1: [2], 2: [4], 3: [4] },
    ask: [{ at: 3, text: "Where should the grid factor come from?", options: ["The AI knows it", "The AI searches the web", "A pinned table; the AI only picks an ID"], expected: "Mostly the pinned table; some web search." }],
    expectedAudience: ["Web search is a common pick; answer: the result has no fixed edition and may not be for the reporting year."],
    revealOrder: ["Pinned factor table", "Rules 1 to 3", "Rules 4 to 6, approval line", "Room vote", "Answer C, {last_year_factor_effect_t} effect"],
    cut: "Skip the vote; read rule 4 aloud.",
    appendixRoutes: ["appendix-factors", "appendix-scope2-order"],
  },

  "two-scope-2": {
    purpose: "Report both Scope 2 figures; guarantees of origin count only for the kWh they cover.",
    mode: "vote",
    clock: { start: "38:30", end: "44:00" },
    say: [
      "Must say: Under the GHG Protocol, a company buying power in a market with certificates and supplier contracts, such as Germany, reports both Scope 2 figures. Which Scope 2 method the VSME Basic Module asks for: check the EFRAG text before the session (appendix A4).",
      "On press 2: location-based uses the grid average where the power is used; market-based uses what you bought. The guarantees of origin cover Werk Süd only.",
      "On press 3: for power without guarantees of origin, use a qualifying supplier rate if there is one, otherwise the residual mix. In Germany the residual mix is usually above the grid average, because the green attributes sold as guarantees of origin are taken out of it.",
      "On press 5: the guarantees of origin take {bridge_cert_t|abs} tonnes out; the residual mix on the other {el_uncovered_mwh|bare} megawatt hours puts {bridge_rm_t|abs} back.",
      "On press 6: so market-based is only {bridge_net_t|abs} tonnes lower. Do not let one plant's green power turn into a sentence about the whole company.",
    ],
    sayAt: { 0: [0], 1: [2], 2: [3], 3: [5], 4: [6] },
    ask: [
      { at: 1, text: "How do you calculate market-based Scope 2?", options: ["0 for the whole company", "0 for Werk Süd, grid average for the rest", "0 for Werk Süd, residual mix for the rest, and location-based too"], expected: "Split between B and C." },
      { at: 4, text: "How far below location-based is market-based?", options: ["About 500 t", "Zero", "About 20 t"], expected: "Most say about 500 t." },
    ],
    expectedAudience: ["Most expect a big drop from the green tariff; the {bridge_net_t|absunit} is the surprise."],
    revealOrder: ["Guarantees of origin card, {renewable_share_el_pct} bar", "Vote 1", "Both Scope 2 numbers", "Wrong options, claim line", "Vote 2", "Bridge bars", "{bridge_net_t|absunit} line"],
    cut: "Skip vote 2; show the bridge directly.",
    appendixRoutes: ["appendix-scope2-order"],
  },
};
