// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../../../kurse/open-source/codex/kurs/[lessonId]/page";
export const dynamicParams = false;
