// GENERATED by scripts/generate-english-route-mirror.mjs.
export { default, generateMetadata, generateStaticParams } from "../../../../../kurse/open-source/data-engineering-fundamentals/[chapterId]/page";
export const dynamicParams = false;
